---
# build the docker image, if needed
- shell: "cat /opt/ipfs.ref | grep {{ ipfs_ref }}"
  ignore_errors: true
  register: ipfs_ref_present
- git:
    repo: https://github.com/ipfs/go-ipfs.git
    dest: /opt/ipfs/src
    version: "{{ ipfs_ref }}"
    force: yes
  when: "ipfs_ref_present.rc != 0"
- copy:
    src: Dockerfile
    dest: /opt/ipfs/src/Dockerfile
  when: "ipfs_ref_present.rc != 0"
- shell: "docker build -t ipfs:{{ ipfs_ref }} /opt/ipfs/src"
  when: "ipfs_ref_present.rc != 0"
- shell: "echo {{ ipfs_ref }} > /opt/ipfs.ref"
  when: "ipfs_ref_present.rc != 0"

# generate ipfs repo
- command: "docker run -i -v /ipfs/ipfs_master:/ipfs ipfs:{{ ipfs_ref }} sh -c 'IPFS_PATH=/ipfs/repo ipfs init'"
  args:
    creates: /ipfs/ipfs_master/repo
- name: install ipfs config
  template:
    src: config.j2
    dest: /ipfs/ipfs_master/repo/config
    mode: 0400
  register: ipfs_config

# assert ipfs container runs and is up-to-date
# XXX: this restarts the container on every run, somehow...
- docker:
    name: ipfs
    image: "ipfs:{{ ipfs_ref }}"
    state: reloaded
    command: ipfs daemon --enable-gc
    restart_policy: always
    ports:
    - 0.0.0.0:4001:4001
    - 127.0.0.1:5001:5001
    - 127.0.0.1:8080:8080
    volumes:
    - /ipfs/ipfs_master:/ipfs
    env:
      IPFS_PATH: /ipfs/repo
      IPFS_LOGGING: debug
- docker:
    name: ipfs
    image: "ipfs:{{ ipfs_ref }}"
    state: restarted
  when: ipfs_config.changed

# nginx vhost for :5001 and :8080 (api/gateway)
- file: path=/opt/nginx/conf.d state=directory
- template:
    src: nginx_ipfs.conf.j2
    dest: /opt/nginx/conf.d/ipfs.conf
  notify: reload nginx


# restart the ipfs container every 30 minutes, with a 25 % chance
- copy:
    src: files/maybe-restart.sh
    dest: /ipfs/maybe-restart.sh
    mode: 755
- cron:
    job: /ipfs/maybe-restart.sh 25 docker restart ipfs
    minute: 55,25
    hour: "*"
    state: present
    name: maybe-restart
    cron_file: ipfs-maybe-restart
    user: root
  when: "inventory_hostname in groups[gateway_group]"
